#!/bin/bash

if ! getent group openakc >/dev/null ; then
  if ! getent group 889 >/dev/null ; then
    groupadd -r -g 889 openakc
  else
    groupadd -r openakc
  fi
fi
#
if ! getent passwd openakc >/dev/null ; then
    if ! getent passwd 889 >/dev/null ; then
      useradd -r -u 889 -g openakc -d /var/lib/openakc -s /bin/bash -c "OpenAKC" openakc
    else
      useradd -r -g openakc -d /var/lib/openakc -s /bin/bash -c "OpenAKC" openakc
    fi
fi
chage -I -1 -m 0 -M 99999 -E -1 openakc 2> /dev/null 1> /dev/null
chsh -s /bin/nologin openakc 2> /dev/null 1> /dev/null
passwd -u openakc 2> /dev/null 1> /dev/null

#DEBHELPER#

exit 0
